	<link rel="stylesheet"  href="my_Website_CSS.css" >	
	<link rel="icon" type="image/png" href="my_Website/zaz.png" />
	<meta charset="UTF-8" />
	<script>
	  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

	  ga('create', 'UA-67569432-1', 'auto');
	  ga('send', 'pageview');

	</script>
